# escape=`



ARG BASE_IMAGE
ARG BUILD_IMAGE



FROM ${BUILD_IMAGE} AS prep
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]



# Gather only artifacts necessary for NuGet restore, retaining directory structure
COPY *.sln NuGet.config Directory.Build.targets Packages.props \nuget\
COPY src\Feature \temp\Feature
COPY src\Foundation \temp\Foundation
COPY src\Project \temp\Project



RUN Invoke-Expression 'robocopy C:\temp C:\nuget\src /s /ndl /njh /njs *.csproj *.scproj packages.config'



FROM ${BUILD_IMAGE} AS builder



ARG BUILD_CONFIGURATION



SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]



# Create an empty working directory
WORKDIR C:\build



# Copy prepped NuGet artifacts, and restore as distinct layer to take better advantage of caching
COPY --from=prep .\nuget .\




# Copy remaining source code
COPY src\Feature .\src\Feature
COPY src\Foundation .\src\Foundation
COPY src\Project .\src\Project



# Copy remaining source code
COPY publishsettings.targets publishsettings.targets



# Copy transforms, retaining directory structure
RUN Invoke-Expression 'robocopy C:\build\src C:\out\transforms /s /ndl /njh /njs *.xdt'



# Build website with file publish
# RUN msbuild .\src\Project\Common\code\KC.Project.Common.csproj /p:Configuration=$env:BUILD_CONFIGURATION /p:DeployOnBuild=True /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:PublishUrl=C:\out\website



# Build XConnect with file publish
# RUN msbuild .\src\Project\KCGov\code\KCGov.Project.Website.csproj /p:Configuration=$env:BUILD_CONFIGURATION /p:DeployOnBuild=True /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:PublishUrl=C:\out\xconnect



#RUN nuget restore



#RUN msbuild KingCounty.Sitecore.sln /t:Build /p:Configuration='Azure Dev' /p:Platform='Any CPU' /p:PublishUrl=C:\out\website



RUN nuget restore -SolutionDirectory C:\build -PackagesDirectory C:\build\packages



RUN msbuild KingCounty.Sitecore.sln /t:Build /p:Configuration='Azure Dev' /p:Platform='Any CPU' /p:DeployOnBuild=True /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:PublishUrl=C:\out\website



RUN Copy-Item -Path C:\build\src\Project\LHWMP\code\LHWMP.Project.Website\Web.config -Destination C:\out\website\Web.config




RUN dir C:\out\website





FROM ${BASE_IMAGE}



WORKDIR C:\artifacts



# Copy final build artifacts
COPY --from=builder C:\out\website .\website\
COPY --from=builder C:\out\transforms .\transforms\
#COPY --from=builder C:\out\xconnect .\xconnect\
